# Generated by Django 4.2.3 on 2023-08-06 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu_isim', models.CharField(max_length=50, verbose_name='Konu')),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=50, verbose_name='Soyisim')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('sifre', models.CharField(max_length=100, verbose_name='Şifre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergi.konu')),
            ],
        ),
        migrations.CreateModel(
            name='Yazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Yazı Başlığı')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 6, 15, 40, 8, 54372, tzinfo=datetime.timezone.utc), verbose_name='Gönderilme Tarihi')),
                ('likes', models.IntegerField(default=0, verbose_name='Beğeni Sayısı')),
                ('yazi_image', models.ImageField(upload_to='', verbose_name='Yazı Footğrafı')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergi.yazar')),
            ],
        ),
    ]
