# Generated by Django 4.2.3 on 2023-08-05 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30, verbose_name='Yazar ismi')),
                ('title', models.CharField(max_length=100, verbose_name='Yazı Başlığı')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 23, 41, 254241), verbose_name='Gönderilme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Begeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Begeni')),
                ('yazi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dergi.yazi')),
            ],
        ),
    ]
