# Generated by Django 4.2.3 on 2023-08-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 15, 41, 9, 281635, tzinfo=datetime.timezone.utc), verbose_name='Gönderilme Tarihi'),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='yazi_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Yazı Footğrafı'),
        ),
    ]
