# Generated by Django 4.2.3 on 2023-08-14 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 53, 44, 862648, tzinfo=datetime.timezone.utc), verbose_name='Gönderilme Tarihi'),
        ),
    ]
