# Generated by Django 4.2.4 on 2023-08-06 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dergi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yazi",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 6, 7, 52, 57, 421025, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Gönderilme Tarihi",
            ),
        ),
    ]
