# Generated by Django 4.2.3 on 2023-08-05 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dergi', '0002_alter_yazi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 24, 11, 942065), verbose_name='Gönderilme Tarihi'),
        ),
    ]
