# Generated by Django 4.2.3 on 2023-09-06 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 19, 40, 97763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 19, 40, 97763, tzinfo=datetime.timezone.utc)),
        ),
    ]
