# Generated by Django 4.2.3 on 2023-09-01 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='isim',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.kategori'),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 20, 29, 19, 777449, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 20, 29, 19, 778449, tzinfo=datetime.timezone.utc)),
        ),
    ]
