# Generated by Django 4.2.4 on 2023-08-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yazar",
            name="status",
        ),
        migrations.AddField(
            model_name="yazar",
            name="category",
            field=models.CharField(
                choices=[
                    ("hikaye", "hikaye"),
                    ("tekonolji", "teknoloji"),
                    ("ekonomi", "ekonomi"),
                    ("mutfak", "mutfak"),
                ],
                default="teknoloji",
                max_length=100,
            ),
        ),
    ]
