# Generated by Django 4.2.3 on 2023-09-04 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='height',
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AddField(
            model_name='yazar',
            name='image',
            field=models.ImageField(default='/static/images/default_user_image.jpg', height_field='height', upload_to='static/images/yazarlar/<built-in function id>', width_field='width'),
        ),
        migrations.AddField(
            model_name='yazar',
            name='width',
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 9, 18, 17, 311473, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 9, 18, 17, 312473, tzinfo=datetime.timezone.utc)),
        ),
    ]
