# Generated by Django 4.2.3 on 2023-09-05 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kategori",
            old_name="isim",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="yazar",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 12, 37, 21, 688140, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="yazi",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 12, 37, 21, 690064, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
