# Generated by Django 4.2.3 on 2023-09-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_kategori_isim_alter_yazar_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 21, 22, 45, 298667, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 21, 22, 45, 300669, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='image',
            field=models.ImageField(default='/static/images/default_user_image.jpg', upload_to='static/images/yazilar/'),
        ),
    ]
