<<<<<<< HEAD:user/migrations/0003_alter_yazar_image_alter_yazar_start_date_and_more.py
# Generated by Django 4.2.3 on 2023-09-06 12:10
=======
# Generated by Django 4.2.3 on 2023-09-05 13:26
>>>>>>> 470ee198ef6298af6f0ab09247a08b12c6be1710:user/migrations/0003_alter_yazar_start_date_alter_yazi_created_date_and_more.py

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD:user/migrations/0003_alter_yazar_image_alter_yazar_start_date_and_more.py
        ('user', '0002_yazar_height_yazar_image_yazar_width_and_more'),
=======
        ("user", "0002_rename_isim_kategori_name_alter_yazar_start_date_and_more"),
>>>>>>> 470ee198ef6298af6f0ab09247a08b12c6be1710:user/migrations/0003_alter_yazar_start_date_alter_yazi_created_date_and_more.py
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD:user/migrations/0003_alter_yazar_image_alter_yazar_start_date_and_more.py
            model_name='yazar',
            name='image',
            field=models.ImageField(default='C:\\Users\\ubeyd\\Projects\\dergi_project\\yenisafak/static/images/default_user_image.jpg', height_field='height', upload_to='static/images/yazarlar', width_field='width'),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 10, 18, 29598, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 10, 18, 29598, tzinfo=datetime.timezone.utc)),
=======
            model_name="yazar",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 13, 26, 42, 733782, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="yazi",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 13, 26, 42, 735881, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="yazi",
            name="image",
            field=models.ImageField(
                default="default_user_image.jpg", upload_to="images/"
            ),
>>>>>>> 470ee198ef6298af6f0ab09247a08b12c6be1710:user/migrations/0003_alter_yazar_start_date_alter_yazi_created_date_and_more.py
        ),
    ]
