# Generated by Django 4.2.4 on 2023-08-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_yazar_status_yazar_category"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="yazar",
            managers=[],
        ),
        migrations.AlterField(
            model_name="yazar",
            name="category",
            field=models.CharField(
                choices=[
                    ("hikaye", "hikaye"),
                    ("mutfak", "mutfak"),
                    ("tekonoloji", "teknoloji"),
                    ("ekonomi", "ekonomi"),
                ],
                default="teknoloji",
                max_length=100,
            ),
        ),
    ]
