# Generated by Django 4.2.3 on 2023-09-06 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_yazar_height_yazar_image_yazar_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazar',
            name='image',
            field=models.ImageField(default='C:\\Users\\ubeyd\\Projects\\dergi_project\\yenisafak/static/images/default_user_image.jpg', height_field='height', upload_to='static/images/yazarlar', width_field='width'),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 10, 18, 29598, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 10, 18, 29598, tzinfo=datetime.timezone.utc)),
        ),
    ]
