# Generated by Django 4.2.4 on 2023-08-29 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_yazar_managers_alter_yazar_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="yazar",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 29, 6, 46, 52, 757564, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="yazar",
            name="category",
            field=models.CharField(
                choices=[
                    ("mutfak", "mutfak"),
                    ("teknoloji", "teknoloji"),
                    ("ekonomi", "ekonomi"),
                    ("hikaye", "hikaye"),
                ],
                default="teknoloji",
                max_length=100,
            ),
        ),
    ]
