# Generated by Django 4.2.3 on 2023-08-30 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_yazar_category_alter_yazar_start_date_yazi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazi',
            name='image',
        ),
        migrations.AlterField(
            model_name='yazar',
            name='category',
            field=models.CharField(choices=[('ekonomi', 'ekonomi'), ('hikaye', 'hikaye'), ('teknoloji', 'teknoloji'), ('mutfak', 'mutfak')], default='teknoloji', max_length=100),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 18, 39, 56, 802310, tzinfo=datetime.timezone.utc)),
        ),
    ]
