# Generated by Django 4.2.3 on 2023-08-30 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_yazi_image_alter_yazar_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 20, 39, 43, 242630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='category',
            field=models.CharField(choices=[('hikaye', 'hikaye'), ('ekonomi', 'ekonomi'), ('mutfak', 'mutfak'), ('teknoloji', 'teknoloji')], default='teknoloji', max_length=100),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 20, 39, 43, 242630, tzinfo=datetime.timezone.utc)),
        ),
    ]
