# Generated by Django 4.2.3 on 2023-08-30 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_yazi_created_date_alter_yazar_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazi',
            old_name='icerik',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='yazi',
            old_name='baslik',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='yazar',
            name='category',
            field=models.CharField(choices=[('teknoloji', 'teknoloji'), ('mutfak', 'mutfak'), ('hikaye', 'hikaye'), ('ekonomi', 'ekonomi')], default='teknoloji', max_length=100),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 20, 46, 27, 380008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 20, 46, 27, 380008, tzinfo=datetime.timezone.utc)),
        ),
    ]
